USE biota_sociobiodiversidade;

INSERT INTO tipo_pp (nome) VALUES
('Resolução'),
('Decreto'),
('Lei'),
('Portaria'),
('Programa'),
('Relatório'),
('Constituição');

INSERT INTO instituicao (nome) VALUES
('Secretaria de Infraestrutura e Meio Ambiente - SP'),
('Secretaria do Meio Ambiente - SP'),
('Secretaria do Meio Ambiente, Infraestrutura e Logistica - SP'),
('Secretaria de Agricultura e Abastecimento - SP'),
('Governo do Estado de São Paulo'),
('Assembleia Legislativa do Estado de São Paulo'),
('kkkkkk'),
('Ministério do Meio Ambiente'),
('Ministério do Meio Ambiente e Mudança do Clima'),
('Ministério da Agricultura'),
('Ministério da Agricultura e Pecuária '),
('Presidência da República - Subchefia para Assuntos Jurídicos'),
('Presidência da República - Casa Civil'),
('Presidência da República - Secretaria-Geral'),
('Câmara dos deputados'),
('Governo Federal do Brasil');

INSERT INTO dominio (nome) VALUES
('Estadual'),
('Federal');

INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 121, DE 12 DE NOVEMBRO DE 2021', 'Substitui membro do Grupo de Trabalho de Gestão Energética - GTGE, instituído pela Resolução SIMA nº 62, de 02 de junho de 2021.', 'SÃO PAULO (Estado). Secretaria de Infraestrutura e Meio Ambiente. Resolução SIMA nº 121, de 12 de novembro de 2021. Substitui membro do Grupo de Trabalho de Gestão Energética - GTGE, instituído pela Resolução SIMA nº 62, de 02 de junho de 2021. Diário Oficial do Estado de São Paulo, São Paulo, SP, 13 nov 2021. Seção 1, p. 109.', 'https://www.imprensaoficial.com.br/DO/BuscaDO2001Documento_11_4.aspx?link=%2f2021%2fexecutivo+secao+i%2fnovembro%2f13%2fpag_0109_a47c7032490e26b03614e606b8297aff.pdf&pagina=109&data=13/11/2021&caderno=Executivo%20I&paginaordenacao=100109', 1, 1, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 66.550, DE 07 DE MARÇO DE 2022', 'Reorganiza o “Programa Remanescentes Florestais”, de que tratam o artigo 23 da Lei nº. 13.798, de 9 de novembro de 2009, e os artigos 51 a 67 do Decreto nº. 55.947, de 24 de junho de 2010, passando a denominar-se “Programa REFLORESTA-SP”, e reorganiza o “Programa de Incentivos à Recuperação de Matas Ciliares e à Recomposição de Vegetação nas Bacias Formadoras de Mananciais de Água – Nascentes”, de que trata o Decreto nº. 62.914, de 8 de novembro de 2017, passando a denominar-se “Programa Nascentes”, e dá providências correlatas;', 'SÃO PAULO (Estado). Governo do Estado de São Paulo. Decreto nº. 66.550, de 07 de março de 2022.Reorganiza o “Programa Remanescentes Florestais”, de que tratam o artigo 23 da Lei nº. 13.798, de 9 de novembro de 2009, e os artigos 51 a 67 do Decreto nº. 55.947, de 24 de junho de 2010, passando a denominar-se “Programa REFLORESTA-SP”, e reorganiza o “Programa de Incentivos à Recuperação de Matas Ciliares e à Recomposição de Vegetação nas Bacias Formadoras de Mananciais de Água – Nascentes”, de que trata o Decreto nº. 62.914, de 8 de novembro de 2017, passando a denominar-se “Programa Nascentes”, e dá providências correlatas. Diário Oficial do Estado de São Paulo, 08 mar 2022 . Seção 1, p. 3.', 'https://www.al.sp.gov.br/repositorio/legislacao/decreto/2022/decreto-66550-07.03.2022.html', 2, 6, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 9.985, DE 18 DE JULHO DE 2000', 'Regulamenta o art. 225, § 1o, incisos I, II, III e VII da Constituição Federal, institui o Sistema Nacional de Unidades de Conservação da Natureza e dá outras providências.', 'BRASIL. Presidência da República. Casa Civil. Lei n° 9.985, de 18 de julho de 2000.  Regulamenta o art. 225, § 1o, incisos I, II, III e VII da Constituição Federal, institui o Sistema Nacional de Unidades de Conservação da Natureza e dá outras providências. Diário Oficial da União, Brasília, DF,  19 jul 2000, p. 1.', 'https://www.planalto.gov.br/ccivil_03/leis/l9985.htm', 3, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 4.340 DE 22 DE AGOSTO DE 2002', 'Regulamenta os artigos da lei Nº 9.985, de 18 de julho de 2000, que dispõe sobre o sistema nacional de unidades de conservação da natureza - SNUC, E DÁ OUTRAS PROVIDÊNCIAS.', 'BRASIL.  Presidência da República. Casa Civil. Decreto nº 4.339 de 22 de agosto de 2022. Regulamenta artigos da lei nº 9.985, de 18 de julho de 2000, que dispõe sobre o Sistema Nacional de Unidades de Conservação da Natureza - SNUC, e dá outras providências. Diário Oficial da União, Brasília, DF, 23 ago 2022, p. 9.', 'https://www.planalto.gov.br/ccivil_03/decreto/2002/D4340.htm', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 55.947, DE 24 DE JUNHO DE 2010', 'Regulamenta a Lei nº 13.798, de 9 de novembro de 2009, que dispõe sobre a Política Estadual de Mudanças Climáticas. ', 'SÃO PAULO (Estado). Governo do Estado de São Paulo. decreto nº 55.947, de 24 de junho de 2010. Regulamenta a Lei nº 13.798, de 9 de novembro de 2009, que dispõe sobre a Política Estadual de Mudanças Climáticas. Diário Oficial do Estado de São Paulo, 25 jun 2010. Seção 1, p.1.', 'https://www.al.sp.gov.br/repositorio/legislacao/decreto/2010/decreto-55947-24.06.2010.html', 2, 5, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 443, DE 17 DE DEZEMBRO DE 2014', 'Reconhece como espécies da flora brasileira ameaçadas de extinção aquelas constantes da “Lista Nacional Oficial de Espécies da Flora Ameaçadas de Extinção”. ', 'BRASIL. Ministério do Meio Ambiente. Portaria MMA nº 443, de 17 de dezembro de 2014. Reconhece como espécies da flora brasileira ameaçadas de extinção aquelas constantes da “Lista Nacional Oficial de Espécies da Flora Ameaçadas de Extinção”. Diário Oficial da União, 18 dez 2014. Seção 1, p. 110-121.', 'https://idaf.es.gov.br/Media/idaf/Documentos/Legisla%C3%A7%C3%A3o/GELCOF/PORTARIA%20MMA%20N%C2%BA%20443,%20DE%2017%20DE%20DEZEMBRO%20DE%202014.pdf', 4, 8, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 057, DE 05 DE JUNHO DE 2016', 'Publica a segunda revisão da lista oficial das espécies da flora ameaçadas de extinção no Estado de São Paulo.', 'SÃO PAULO (Estado). Secretaria do Meio Ambiente. Resolução SMA nº 057, de 05 de junho de 2016. Publica a segunda revisão da lista oficial das espécies da flora ameaçadas de extinção no Estado de São Paulo. Diário Oficial do Estado de São Paulo, São Paulo, 30 jun 2016. Seção 1, p. 55-57.', 'https://smastr16.blob.core.windows.net/legislacao/sites/262/2022/07/2016resolucao_sma_057_2016-1.pdf', 1, 2, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 20, DE 27 DE SETEMBRO DE 1976', 'Proíbe o abate de pinheiros adultos (Araucaria angustifolia), portadores de pinhas, nos meses de abril, maio e junho.', 'BRASIL. Ministério da Agricultura. Instituto Brasileiro de Desenvolvimento Florestal (IDBF). Portaria Normativa DC nº 20, de 27 de setembro de 1976. Proíbe o abate de pinheiros adultos (Araucaria angustifolia), portadores de pinhas, nos meses de abril, maio e junho. Diário Oficial, 06 out 1976.', 'https://www.ibama.gov.br/sophia/cnia/legislacao/IBDF/PT0020-200976.PDF', 4, 10, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 57.755, DE 24 DE JANEIRO DE 2012', 'Programa Paulista da Agricultura de Interesse Social – PPAIS', 'SÃO PAULO (Estado). Secretaria de Desenvolvimento Econômico. Resolução SDE nº 57.755, de 24 de junho de 2024. Regulamenta o Programa Paulista da Agricultura de Interesse Social – PPAIS. Diário Oficial do Estado de São Paulo, São Paulo, 25 jun 2024. Seção 1, p. 11.', 'https://www.itesp.sp.gov.br/wp-content/uploads/2024/08/decreto-n.57.755-de-24.01.2012.pdf', 2, 5, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('N° 7.644, DE 16 DE DEZEMBRO DE 2011', 'Programa de Fomento às Atividades Produtivas Rurais', 'BRASIL. Presidência da República. Casa Civil. Decreto n° 7.644, de 16 de Dezembro de 2011. Institui oPrograma de Fomento às Atividades Produtivas Rurais. Diário Oficial da União, Brasília, DF,  19 dez 2011, p. 4. ', 'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/decreto/d7644.htm', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 045, DE 27 DE MAIO DE 2022', 'Organiza a Unidade de Coordenação do “Programa REFLORESTA-SP”, prevista no artigo 3º do Decreto estadual nº. 66.550, de 07 de março de 2022, e dá outras providências;', 'SÃO PAULO (Estado). Secretaria de Infraestrutura e Meio Ambiente. Resolução SIMA nº 045, de 27 de maio de 2022. Organiza a Unidade de Coordenação do “Programa REFLORESTA-SP”, prevista no artigo 3º do Decreto estadual nº. 66.550, de 07 de março de 2022, e dá outras providências. Diário Oficial do Estado de São Paulo, São Paulo, 28 mai 2022 . Seção 1, p. 71.', 'https://smastr16.blob.core.windows.net/legislacao/sites/262/2022/08/resolucao_sima_045_2022.pdf', 1, 1, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 4.339 DE 22 DE AGOSTO DE 2002', 'Institui princípios e diretrizes para a implementação da Política Nacional da Biodiversidade', 'BRASIL.  Presidência da República. Casa Civil. Decreto nº 4.339 de 22 de agosto de 2002. Institui princípios e diretrizes para a implementação da Política Nacional da Biodiversidade. Diário Oficial da União, Brasília, DF, 23 ago 2002, p. 2.', 'https://www.planalto.gov.br/ccivil_03/decreto/2002/d4339.htm', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 54.654 DE 7 DE AGOSTO DE 2009', 'Institui o Programa Estadual de Fomento aos Arranjos Produtivos Locais, autoriza a celebração de convênios com municípios do Estado de São Paulo e entidades que especifica, visando à transferência de recursos financeiros para o incremento das cadeias produtivas, e dá providências correlatas', 'SÃO PAULO (Estado). Governo do Estado de São Paulo. Decreto nº 54.654 de 7 de agosto de 2009. Institui o Programa Estadual de Fomento aos Arranjos Produtivos Locais, autoriza a celebração de convênios com municípios do Estado de São Paulo e entidades que especifica, visando à transferência de recursos financeiros para o incremento das cadeias produtivas, e dá providências correlatas. Diário Oficial do Estado de São Paulo, 08 ago 2009. Seção 1, p.1-3.', 'https://www.al.sp.gov.br/repositorio/legislacao/decreto/2009/decreto-54654-07.08.2009.html', 2, 5, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('N° 12.512, DE 14 DE OUTUBRO DE 2011', 'Institui o Programa de Apoio à Conservação Ambiental e o Programa de Fomento às Atividades Produtivas Rurais; altera as Leis nºs 10.696, de 2 de julho de 2003, 10.836, de 9 de janeiro de 2004, e 11.326, de 24 de julho de 2006.', 'BRASIL. Presidência da República. Casa Civil. Lein° 12.512, de 14 de outubro de 2011.  Institui o Programa de Apoio à Conservação Ambiental e o Programa de Fomento às Atividades Produtivas Rurais; altera as Leis nºs 10.696, de 2 de julho de 2003, 10.836, de 9 de janeiro de 2004, e 11.326, de 24 de julho de 2006.. Diário Oficial da União, Brasília, DF,  17 out 2021, p. 1. ', 'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12512.htm', 3, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('N° 5.758, DE 13 DE ABRIL DE 2006', 'INSTITUI O PLANO ESTRATÉGICO NACIONAL DE ÁREAS PROTEGIDAS - PNAP, SEUS PRINCÍPIOS, DIRETRIZES, OBJETIVOS E ESTRATÉGIAS, E DÁ OUTRAS PROVIDÊNCIAS.', 'BRASIL. Presidência da República. Casa Civil. Decreto n° 5.758, de 13 de abril de 2006. Institui o Plano Estratégico Nacional de Áreas Protegidas - PNAP, seus princípios, diretrizes, objetivos e estratégias, e dá outras providências. Diário Oficial da União, Brasília, DF, 17 abr 2006, p. 1.', 'https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/decreto/d5758.htm', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº. 03, DE 02 DE MARÇO DE 2023', 'Institui o Aplicativo Refloresta-SP, cria o Comitê Técnico-Científico do Aplicativo Refloresta-SP e dá outras providências;', 'SÃO PAULO (Estado). Secretaria do Meio Ambiente, Infraestrutura e Logística. Resolução SEMIL nº.  03, de 02 de março de 2023. Institui o Aplicativo Refloresta-SP, cria o Comitê Técnico-Científico do Aplicativo Refloresta-SP e dá outras providências. Diário Oficial do Estado de São Paulo, São Paulo, 18 mar 2023 . Seção 1, p. 44.', 'https://smastr16.blob.core.windows.net/legislacao/sites/5/2024/04/RESOLUCAO-SEMIL-003-2023-PAGINA-44.pdf', 1, 3, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 14.119, DE 13 DE JANEIRO DE 2021', 'Institui a Política Nacional de Pagamento por Serviços Ambientais; e altera as Leis nºs 8.212, de 24 de julho de 1991, 8.629, de 25 de fevereiro de 1993, e 6.015, de 31 de dezembro de 1973, para adequá-las à nova política.', 'BRASIL. Presidência da República. Lei nº 14.119, de 13 de janeiro de 2021. Institui a Política Nacional de Pagamento por Serviços Ambientais; e altera as Leis nºs 8.212, de 24 de julho de 1991, 8.629, de 25 de fevereiro de 1993, e 6.015, de 31 de dezembro de 1973, para adequá-las à nova política.', 'https://www.planalto.gov.br/ccivil_03/_Ato2019-2022/2021/Lei/L14119.htm', 3, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('N° 7.747, DE 5 DE JUNHO DE 2012', 'Institui a Política Nacional de Gestão Territorial e Ambiental de Terras Indígenas. ', 'BRASIL. Presidência da República. Casa Civil. Decreto n° 7.747, de 5 de junho de 2012.  Institui a Política Nacional de Gestão Territorial e Ambiental de Terras Indígenas. Diário Oficial da União, Brasília, DF,  06 jun 2012, p. 9. ', 'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2012/decreto/d7747.htm', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('N° 6.040, DE 7 DE FEVEREIRO DE 2007', 'Institui a Política Nacional de Desenvolvimento Sustentável dos Povos e Comunidades Tradicionais. ', 'BRASIL. Presidência da República. Casa Civil. Decreto n° 6.040, de 07 de fevereiro de 2007. Institui a Política Nacional de Desenvolvimento Sustentável dos Povos e Comunidades Tradicionais. Diário Oficial da União, Brasília, DF,  08 fev 2007, p. 316.', 'http://www.planalto.gov.br/ccivil_03/_ato2007-2010/2007/decreto/d6040.htm', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 13.798, DE 09 DE NOVEMBRO DE 2009', 'Institui a Política Estadual de Mudanças Climáticas – PEMC;', 'SÃO PAULO (Estado).Governo do Estado de São Paulo. Lei nº. 13.798, de 09 de novembro de 2009. Institui a Política Estadual de Mudanças Climáticas – PEMC.  Diário Oficial do Estado de São Paulo, São Paulo, 10 nov 2009 . Seção 1, p. 1-4.', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2009/lei-13798-09.11.2009.html', 3, 5, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 9.989, DE 21 DE JULHO DE 2000', 'Id. Ministério do Orçamento, Planejamento e Gestão. Plano Plurianual (PPA): 2000-2003, relatório anual de avaliação, exercício 2001. Brasília, 2001.', 'BRASIL. Presidência da República. Lei nº 9.989, de 21 de julho de 2000. Dispõe sobre o Plano Plurianual para o período de 2000/2003. Diário Oficial da União, Brasília, DF, 24 jul 2000.', 'https://www.planalto.gov.br/ccivil_03/Leis/L9989.htm#:~:text=LEI%20No%209.989%2C%20DE%2021%20DE%20JULHO%20DE%202000.&text=Disp%C3%B5e%20sobre%20o%20Plano%20Plurianual,cumprimento%20ao%20disposto%20no%20art. ;  https://www.gov.br/planejamento/pt-br/assuntos/planejamento/plano-plurianual/paginas/ppa-2000-2003', 3, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 4.703, DE 21 DE MAIO DE 2003', 'Id. Ministério do Meio Ambiente. Sumário executivo das áreas prioritárias para a conservação, utilização sustentável e repartição de benefícios da biodiversidade brasileira. Brasília: MMA, 2007.', 'BRASIL. Ministério do Meio Ambiente (MMA). Decreto nº 5.094, de 3 de junho de 2004. Diário Oficial da União, Brasília, DF, 4 jun 2004, Seção 1, p. 7. ', 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biomas-e-ecossistemas/conservacao-1/areas-prioritarias/Delib_040.pdf ; https://www.planalto.gov.br/ccivil_03/decreto/2003/D4703compilado.htm', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 2.519, DE 16 DE MARÇO DE 1998', 'Convenção sobre Diversidade Biológica', 'BRASIL. Ministério do Meio Ambiente. Quarto Relatório Nacional para a Convenção sobre Diversidade Biológica. Brasília: MMA, 2010.', 'https://www.planalto.gov.br/ccivil_03/decreto/d2519.htm ; https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/biodiversidade1/convencao-sobre-diversidade-biologica', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 9.985, DE 18 DE JULHO DE 2000', 'Sistema Nacional de Unidades de Conservação da Natureza — SNUC.', 'BRASIL. Presidência da República. Decreto nº 2.519, de 16 de março de 1998. Promulga a Convenção sobre Diversidade Biológica, assinada no Rio de Janeiro, em 05 de junho de 1992. Diário Oficial da União, Brasília, DF, 17 mar 1998. Seção 1, p. 1. ____. Ministério do Meio Ambiente. Quarto Relatório Nacional para a Convenção sobre Diversidade Biológica. Brasília: MMA, 2010.', 'https://www.gov.br/mma/pt-br/assuntos/biodiversidade-e-biomas/areas-protegidas/sistema-nacional-de-unidades-de-conservacao-da-natureza-snuc ; https://www.planalto.gov.br/ccivil_03/leis/l9985.htm', 3, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 12.485, 3 DE JUNHO DE 2025', 'Id. Ministério do Meio Ambiente. Diretrizes e prioridades do plano de ação para implementação da Política Nacional da Biodiversidade. Brasília: MMA, 2006. (Série Biodiversidade, 22).', 'BRASIL. Presidência da República. Decreto nº 12.485, de 3 de junho de 2025. Dispõe sobre a Estratégia e o Plano de Ação Nacionais para a Biodiversidade. Diário Oficial da União, Brasília, DF, 4 jun. 2025. Seção 1, p. 6.____. Ministério do Meio Ambiente. Diretrizes e prioridades do plano de ação para implementação da Política Nacional da Biodiversidade. Brasília: MMA, 2006. (Série Biodiversidade, 22).', 'https://www.gov.br/mma/pt-br/composicao/sbio/departamento-de-conservacao-e-uso-sustentavel-da-biodiversidade/epanb#:~:text=Em%203%20de%20junho%20de,Nacionais%20para%20a%20Biodiversidade%20%2D%20EPANB. ; https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2025/decreto/D12485.htm', 2, 8, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('N º09, DE 23 DE JANEIRO DE 2007', 'Id. Ministério do Meio Ambiente. Biodiversidade Brasileira: Avaliação e identificação de áreas e ações prioritárias para conservação, utilização sustentável e repartição dos benefícios da biodiversidade nos biomas brasileiros. Brasília: MMA, 2002.', 'BRASIL. Ministério do Meio Ambiente. Biodiversidade Brasileira: Avaliação e identificação de áreas e ações prioritárias para conservação, utilização sustentável e repartição dos benefícios da biodiversidade nos biomas brasileiros. Brasília: MMA, 2002.____. Ministério do Meio Ambiente. Portaria MMA nº 9, de 23 de janeiro de 2007. Diário Oficial da União, Brasília, DF, 24 jan. 2007.', 'https://antigo.mma.gov.br/estruturas/chm/_arquivos/2relat_cap3.pdf ; https://abcm.satc.edu.br/wp-content/uploads/2021/09/portaria_mma_09-2007.pdf', 4, 8, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 189, DE 20 DE DEZEMBRO DE 2018', 'Estabelece critérios e procedimentos para exploração sustentável de espécies nativas do Brasil no Estado de São Paulo.', 'SÃO PAULO (Estado). Secretaria do Meio Ambiente. Resolução SMA nº 189, de 20 de dezembro de 2018. Estabelece critérios e procedimentos para exploração sustentável de espécies nativas do Brasil no Estado de São Paulo. Diário Oficial do Estado de São Paulo, São Paulo, SP, 21 dez. 2018. Seção 1, p. 58-61.', 'https://smastr16.blob.core.windows.net/legislacao/sites/262/2022/07/2018resolucao_sma_189_2018.pdf', 1, 2, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('N° 11.326, DE 24 DE JUNHO DE 2006', 'Estabelece as diretrizes para a formulação da Política Nacional da Agricultura Familiar e Empreendimentos Familiares Rurais. ', 'BRASIL. Lei n° 11.326, de 24 de julho de 2006. Estabelece as diretrizes para a formulação da Política Nacional da Agricultura Familiar e Empreendimentos Familiares Rurais. Disponível em: <https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11326.htm>. Acesso em: 26 de julho de 2023.', 'https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11326.htm', 3, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 121, DE 30 DE DEZEMBRO DE 2022', 'Dispõe sobre os procedimentos para a coleta de sementes de pinheiro-brasileiro (Araucaria angustifolia) no Estado de São Paulo. ', 'SÃO PAULO (Estado). Secretaria do Meio Ambiente. Resolução SMA nº 121, de 30 de dezembro de 2022. Dispõe sobre os procedimentos para a coleta de sementes de pinheiro-brasileiro (Araucaria angustifolia) no Estado de São Paulo. Diário Oficial do Estado de São Paulo, 31 dez 2022. Seção 1, p.118.', 'https://smastr16.blob.core.windows.net/2001/2023/11/2022-Resolucao-SIMA-121_-Coleta-de-Pinhao-1.pdf', 1, 1, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 98, DE 26 DE OUTUBRO DE 2022', 'Dispõe sobre os critérios para a concessão de autorizações para a atividade de implantação de roças tradicionais praticadas por povos e comunidades tradicionais no Estado de São Paulo. ', 'SÃO PAULO (Estado). Secretaria de Infraestrutura e Meio Ambiente. Resolução SIMA nº 98, de 26 de outubro de 2022. Dispõe sobre os critérios para a concessão de autorizações para a atividade de implantação de roças tradicionais praticadas por povos e comunidades tradicionais no Estado de São Paulo. Diário Oficial do Estado de São Paulo, São Paulo, SP, 26 out 2022. Seção 1, p. 140-141.', 'https://smastr16.blob.core.windows.net/legislacao/sites/262/2022/10/resolucao_sima_098_2022-republicada.pdf', 1, 1, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('N° 327, DE 9 DE ABRIL DE 2021', 'Dispõe sobre o Programa de Conservação da Palmeira Juçara da Fundação Florestal.', 'SÃO PAULO (Estado). Secretaria de Infraestrutura e Meio Ambiente. Fundação Florestal. Portaria FF n° 327, de 9 de abril de 2021. Dispõe sobre o Programa de Conservação da Palmeira Juçara da Fundação Florestal. Diário Oficial do Estado de São Paulo, 10 abr 2021. Seção 1, p.105.', 'https://fflorestal.sp.gov.br/legislacao/', 4, 1, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('N° 69, DE 06 DE OUTUBRO  2021', 'Dispõe sobre a instituição do Painel de Estudos Aplicados em Arranjos Produtivos Locais Agroindustriais Rurais do Estado de São Paulo.', 'SÃO PAULO (Estado). Secretaria de Agricultura e Abastecimento. Resolução SAA No 69, de  06 de outubro de 2021. Dispõe sobre a instituição do Painel de Estudos Aplicados em  Arranjos Produtivos Locais Agroindustriais Rurais do Estado de São Paulo. Diário  Oficial do Estado de São Paulo, São Paulo,8 de outubro de 2021. Seção 1, 131 (195) 37.', 'https://diariooficial.imprensaoficial.com.br/doflash/prototipo/2021/Outubro/08/exec1/pdf/pg_0037.pdf', 1, 4, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('N° 5.092, DE 21 DE MAIO DE 2004', 'Define regras para identificação de áreas prioritárias para a conservação, utilização sustentável e repartição dos benefícios da biodiversidade, no âmbito das atribuições do Ministério do Meio Ambiente.', 'BRASIL.  Vice-Presidência da República. Casa Civil. Decreto no 5.092, de 21 de maio de 2004. Define regras para identificação de áreas prioritárias para a conservação, utilização sustentável e repartição dos benefícios da biodiversidade, no âmbito das atribuições do Ministério do Meio Ambiente. Diário Oficial da União, Brasília, DF,  24 mai 2004, p. 2.', 'https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2004/decreto/d5092.htm', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('SEXTO', 'Sexto Relatório Nacional para Convenção sobre Diversidade biológica 2023.', 'BRASIL. Ministério do Meio Ambiente e Mudança do Clima. Secretaria de Biodiversidade, Florestas e Direitos Animais.  Coordenador: Rodrigo Martins Vieira. Sexto Relatório Nacional para Convenção sobre Diversidade biológica: Brasil. Brasília, DF: MMA, 2023. Disponível em: <https://www.gov.br/mma/pt-br/assuntos/biodiversidade/publicacoes/6rn>. Acesso em: 25 out 2023.', 'https://www.gov.br/mma/pt-br/mma-lanca-6o-relatorio-nacional-para-cdb-no-dia-da-biodiversidade/6rn.pdf', 6, 8, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('QUINTO', 'Quinto Relatório Nacional para Convenção sobre Diversidade biológica 2015.', 'BRASIL. Ministério do Meio Ambiente. Secretaria de Biodiversidade e Florestas.  Coordenador: Carlos Alberto de Mattos Scaramuzza. Fifth National Report to the Convention on Biological Diversity: Brazil. Brasília, DF: MMA, 2015. Disponível em: <https://www.cbd.int/doc/world/br/br-nr-05-en.pdf>. Acesso em: 25 out 2023.', 'https://www.cbd.int/doc/world/br/br-nr-05-en.pdf', 6, 8, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('QUARTO', 'Quarto Relatório Nacional para Convenção sobre Diversidade biológica 2010.', 'BRASIL. Ministério do Meio Ambiente. Secretaria de Biodiversidade e Florestas.  Coordenador: Braulio Ferreira de Souza Dias. Quarto Relatório Nacional para Convenção sobre Diversidade biológica: Brasil. Brasília, DF: MMA, 2010. Disponível em: <https://www.cbd.int/doc/world/br/br-nr-04-pt.pdf>. Acesso em: 25 out 2023.', 'https://www2.ib.unicamp.br/profs/cjoly/0%20-%20NE441%20%202013/TEXTOS%20DE%20APOIO/4o%20Relat%F3rio%20BRASIL%20%20CBD%202010.pdf', 6, 8, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('TERCEIRO', 'Terceiro Relatório Nacional para Convenção sobre Diversidade biológica 2005.', 'BRASIL. Ministério do Meio Ambiente. Secretaria de Biodiversidade e Florestas. Third National Report to the Convention on Biological Diversity: Brazil. Brasília, DF: MMA, 2005. Disponível em: <https://www.cbd.int/doc/world/br/br-nr-03-en.pdf>. Acesso em: 25 out 2023.', 'CBD Third National Report - Brazil (English version)', 6, 8, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('SEGUNDO', 'Segundo Relatório Nacional para Convenção sobre Diversidade biológica 2004.', 'BRASIL. Ministério do Meio Ambiente. Secretaria de Biodiversidade e Florestas. Coorednador: Braulio Ferreira de Souza Dias. Second National Report to the Convention on Biological Diversity: Brazil. Brasília, DF: MMA, 2004. Disponível em: <https://www.cbd.int/doc/world/br/br-nr-02-p1-en.pdf>. Acesso em: 25 out 2023.', 'https://antigo.mma.gov.br/estruturas/chm/_arquivos/2relat_iniciais.pdf', 6, 8, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('PRIMEIRO', 'Primeiro Relatório Nacional para Convenção sobre Diversidade biológica 1999.', 'BRASIL. Ministério do Meio Ambiente. Secretaria de Biodiversidade e Florestas. Second National Report to the Convention on Biological Diversity: Brazil. Brasília, DF: MMA, 1999. Disponível em: <https://www.cbd.int/doc/world/br/br-nr-01-p1-en.pdf>. Acesso em: 25 out 2023.', 'CBD First National Report - Brazil (Part I, English version); https://www.alice.cnptia.embrapa.br/alice/bitstream/doc/17151/1/1289.pdf', 6, 8, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 42, DE 18 DE ABRIL DE 2018', 'Constitui o Comitê de Integração do Palmito Legal. ', 'SÃO PAULO (Estado). Secretaria do Meio Ambiente. Resolução SMA nº 42, de 18 de abril de 2018. Constitui o Comitê de Integração do Palmito Legal. Diário Oficial do Estado de São Paulo, São Paulo, 19 abr 2018. Seção 1, p. 38.', 'https://smastr16.blob.core.windows.net/legislacao/sites/262/2022/07/2018resolucao_sma_042_2018.pdf', 1, 2, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 6.938, DE 31 DE AGOSTO DE 1981', 'Dispõe sobre a Política Nacional do Meio Ambiente, seus fins e mecanismos de formulação e aplicação, e dá outras providências.', 'BRASIL. Lei nº 6.938, de 31 de agosto de 1981. Dispõe sobre a Política Nacional do Meio Ambiente, seus fins e mecanismos de formulação e aplicação, e dá outras providências. Diário Oficial da União, Brasília, DF, 2 set. 1981. Seção 1, p. 16509.', 'https://www2.camara.leg.br/legin/fed/lei/1980-1987/lei-6938-31-agosto-1981-366135-publicacaooriginal-1-pl.html ', 3, 8, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('1988', 'Constituição Federal de 1988', 'BRASIL. Constituição da República Federativa do Brasil, de 5 de outubro de 1988. Diário Oficial da União, Brasília, DF, 5 out. 1988.', 'https://www.planalto.gov.br/ccivil_03/Constituicao/Constituicao.htm', 7, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 4.339, DE 22 DE AGOSTO DE 2002', 'Política Nacional da Biodiversidade (PNB)', 'BRASIL. Decreto nº 4.339, de 22 de agosto de 2002. Institui princípios e diretrizes para a implementação da Política Nacional da Biodiversidade. Diário Oficial da União, Brasília, DF, 23 ago. 2002.', 'https://www.planalto.gov.br/ccivil_03/decreto/2002/d4339.htm', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 23.793, DE 23 DE JANEIRO DE 1934', 'Código Florestal', ' Decreto nº 23.793, de 23 de janeiro de 1934. Aprova o novo Código Florestal. Diário Oficial da União, Rio de Janeiro, 26 jan. 1934.', 'https://www2.camara.leg.br/legin/fed/decret/1930-1939/decreto-23793-23-janeiro-1934-498279-publicacaooriginal-78167-pe.html', 2, 15, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 24.643, DE 10 DE JULHO DE 1934', 'Código de Águas', 'BRASIL. Decreto nº 24.643, de 10 de julho de 1934. Decreta o Código de Águas. Diário Oficial da União, Rio de Janeiro, 12 jul. 1934.', 'https://www.planalto.gov.br/ccivil_03/decreto/d24643compilado.htm', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 13.123, de 20 de maio de 2015', 'Lei da Biodiversidade', 'BRASIL. Lei nº 13.123, de 20 de maio de 2015. Dispõe sobre o acesso ao patrimônio genético, sobre a proteção e o acesso ao conhecimento tradicional associado e sobre a repartição de benefícios para conservação e uso sustentável da biodiversidade. Diário Oficial da União, Brasília, DF, 21 maio 2015. Seção 1, p. 1.', 'https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13123.htm', 3, 14, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 7.794, DE 20 DE AGOSTO DE 2012', 'Política Nacional de Agroecologia e Produção Orgânica (PNAPO)', 'BRASIL. Decreto nº 7.794, de 20 de agosto de 2012. Institui a Política Nacional de Agroecologia e Produção Orgânica. Diário Oficial da União, Brasília, DF, 21 ago. 2012.', 'https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2012/decreto/d7794.htm', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 5.996, DE 20 DE DEZEMBRO DE 2006', 'Programa de Garantia de Preços para Agricultura Familiar (PGPAF)', 'BRASIL. Decreto nº 5.996, de 20 de dezembro de 2006. Dispõe sobre a criação do Programa de Garantia de Preços para a Agricultura Familiar - PGPAF de que trata a Lei nº 11.326, de 24 de julho de 2006, e o art. 13 da Lei nº 11.322, de 13 de julho de 2006. Diário Oficial da União, Brasília, DF, 21 dez. 2006.', 'https://pesquisa.in.gov.br/imprensa/jsp/visualiza/index.jsp?jornal=1&pagina=2&data=21/12/2006', 2, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 14.628, DE 20 DE JULHO DE 2023', 'Programa de Aquisição de Alimentos (PAA)', 'BRASIL. Lei nº 14.628, de 20 de julho de 2023. Regulamenta o Programa de Aquisição de Alimentos (PAA) e outras disposições. Diário Oficial da União, Brasília, DF, 21 jul. 2023.', 'https://www.planalto.gov.br/ccivil_03/_Ato2023-2026/2023/Lei/L14628.htm', 3, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 11.326, DE 24 DE JULHO DE 2006', 'Estabelece as diretrizes para a formulação da Política Nacional da Agricultura Familiar e Empreendimentos Familiares Rurais.', 'BRASIL. Decreto nº 1.946, de 28 de junho de 1996. Cria o Programa Nacional de Fortalecimento da Agricultura Familiar - PRONAF, e dá outras providências. Diário Oficial da União, Brasília, DF, 1 jul. 1996.', 'https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11326.htm', 3, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 1.946, DE 28 DE JUNHO DE 1996', 'Programa Nacional de Fortalecimento da Agricultura Familiar (PRONAF)', 'BRASIL. Decreto nº 1.946, de 28 de junho de 1996. Cria o Programa Nacional de Fortalecimento da Agricultura Familiar - PRONAF, e dá outras providências. Diário Oficial da União, Brasília, DF, 1 jul. 1996.', 'https://www.planalto.gov.br/ccivil_03/decreto/d1946.htm ', 2, 12, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 239 DE 21 DE JULHO DE 2009', 'Plano Nacional de Promoção das Cadeias de Produtos da Sociobiodiversidade', 'BRASIL. Portaria Interministerial MDA, MDS e MMA nº 239, de 21 de julho de 2009. Estabelece orientações para a implementação do Plano Nacional de Promoção das Cadeias de Produtos da Sociobiodiversidade, e dá outras providências. Diário Oficial da União, Brasília, DF, 22 jul. 2009.', 'https://bibliotecadigital.economia.gov.br/bitstream/123456789/1024/1/Plano%20Sociobiodiversidade.pdf ; https://www.mds.gov.br/webarquivos/legislacao/seguranca_alimentar/_doc/portarias/2009/PCT%20Portaria%20Interministerial%20MDA-%20MDS%20e%20MMA%20no%20239-%20de%2021%20de%20julho%20de%202009.pdf', 4, 16, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 121, DE 18 DE JUNHO DE 2019', 'Programa Bioeconomia Brasil-Sociobiodiversidade', 'BRASIL. Ministério da Agricultura, Pecuária e Abastecimento. Portaria nº 121, de 18 de junho de 2019. Institui o Programa Bioeconomia Brasil-Sociobiodiversidade. Diário Oficial da União, Brasília, DF, 19 jun. 2019.', 'https://www.gov.br/agricultura/pt-br/assuntos/noticias/mapa-seleciona-projetos-para-fortalecer-produtos-e-servicos-da-sociobiodiversidade-brasileira-na-amazonia-legal/copy2_of_Manual_Operacional_do_Sociobio_na_Amazonia.pdf', 4, 10, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 14.802, DE 10 DE JANEIRO DE 2024', 'Plano Plurianual (PPA)', 'BRASIL. Lei nº 14.802, de 10 de janeiro de 2024. Institui o Plano Plurianual da União para o período de 2024 a 2027. Diário Oficial da União, Brasília, DF, 11 jan. 2024.', 'https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/L14802.htm', 3, 13, 2);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('N° 54.654 DE 07 DE AGOSTO DE 2009', 'Programa de Fomento de Arranjos Produtivos Locais Paulista', 'SÃO PAULO. Decreto nº 54.654, de 7 de agosto de 2009. Institui o Programa Estadual de Fomento aos Arranjos Produtivos Locais, autoriza a celebração de convênios com municípios do Estado de São Paulo e entidades que especifica, visando à transferência de recursos financeiros para o incremento das cadeias produtivas, e dá providências correlatas. Diário Oficial do Estado, São Paulo, 8 ago. 2009.', 'https://www.al.sp.gov.br/repositorio/legislacao/decreto/2009/decreto-54654-07.08.2009.html', 2, 6, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 57.402, DE 6 DE OUTUBRO 2011', 'Comissão Paulista da Biodiversidade', 'SÃO PAULO. Decreto nº 57.402, de 6 de outubro de 2011. Institui a Comissão Paulista da Biodiversidade e dá providências correlatas. Diário Oficial do Estado, São Paulo, 7 out. 2011.', 'https://www.al.sp.gov.br/repositorio/legislacao/decreto/2011/decreto-57402-06.10.2011.html', 2, 6, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 66.508, DE 15 DE FEVEREIRO DE 2022', 'Política Estadual de Agroecologia e Produção Orgânica de São Paulo (PEAPO)', 'SÃO PAULO. Lei nº 16.684, de 19 de março de 2018. Institui a Política Estadual de Agroecologia e Produção Orgânica - PEAPO, e dá outras providências. Diário Oficial do Estado, São Paulo, 20 mar. 2018.SÃO PAULO. Decreto nº 66.508, de 15 de fevereiro de 2022. Regulamenta a Lei nº 16.684, de 19 de março de 2018, que institui a Política Estadual de Agroecologia e Produção Orgânica - PEAPO, e dá providências correlatas. Diário Oficial do Estado, São Paulo, 16 fev. 2022.', 'https://www.al.sp.gov.br/repositorio/legislacao/lei/2018/lei-16684-19.03.2018.html ; https://www.al.sp.gov.br/repositorio/legislacao/decreto/2022/decreto-66508-15.02.2022.html', 2, 6, 1);
INSERT INTO politicas_publicas (title, description, bibliographicCitation, references_url, tipoID, instituicaoID, dominioID) VALUES ('Nº 8.427, DE 27 DE MAIO DE 1992', 'Política de Garantia de Preços Mínimos para os Produtos da Sociobiodiversidade (PGPM-Bio)', 'BRASIL. Lei nº 8.427, de 27 de maio de 1992. Dispõe sobre a concessão de subvenção econômica nas operações de crédito rural. Diário Oficial da União, Brasília, 28 mai. 1992. Seção 1, p. 6585.', 'https://www.gov.br/conab/pt-br/atuacao/politica-de-garantia-de-precos-minimos/pgpm-bio/cartilha-pgpm-bio.pdf ; ferramenta: https://www.planalto.gov.br/ccivil_03/leis/l8427.htm', 3, 13, 2);

SELECT 
    pp.resourceID,
    pp.title,
    pp.description,
    t.nome AS tipo,
    i.nome AS instituicao,
    d.nome AS dominio,
    pp.bibliographicCitation,
    pp.references_url
FROM politicas_publicas pp
JOIN tipo_pp t ON pp.tipoID = t.tipoID
JOIN instituicao i ON pp.instituicaoID = i.instituicaoID
JOIN dominio d ON pp.dominioID = d.dominioID
ORDER BY pp.resourceID;
