INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Aroeira-pimenteira//Pimenta-rosa', 'Anacardiaceae', 'Schinus terebinthifolia', 'Raddi  ', 'LC', 'LC', 'Nativa', 'Não', '5-10', 'Pioneira', 'Preenchimento', 'Zoocórica', 'Perene', 'Perenifólia');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Imbé', 'Araceae', 'Philodendron imbe', 'Schott ex Kunth.', 'NULL', 'NE', 'Nativa', 'Sim', 'NULL', 'NULL', 'NULL', 'NULL', 'Perene', 'Perenifólia');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Macaúba', 'Arecaceae', 'Acrocomia aculeata', '(Jacq.) Lodd. ex Mart.', 'NULL', 'NE', 'Nativa', 'Não', '10-15', 'Não Pioneira', 'Preenchimento', 'Zoocórica', 'Perene', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Tucum', 'Arecaceae', 'Bactris setosa', 'Mart.  ', 'LC', 'LC', 'Nativa', 'Sim', '8', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'NULL', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Juçara', 'Arecaceae', 'Euterpe edulis', 'Mart.  ', 'VU', 'VU', 'Nativa', 'Não', '5-12', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'Perene', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Jerivá', 'Arecaceae', 'Syagrus romanzoffiana', '(Cham.) Glassman ', 'LC', 'LC', 'Nativa', 'Não', '7 - 15', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'Anual', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Pinhão', 'Auricariaceae', 'Araucaria angustifolia', '(Bertol.) Kuntze ', 'NULL', 'EN', 'Nativa', 'Não', '20-50', 'Não Pioneira', 'Diversidade', 'Autocórica//Zoocórica', 'Perene', 'Perenifólia');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Caixeta', 'Bignoniaceae', 'Tabebuia cassinoides', '(Lam.) Dc.', 'NULL', 'VU', 'Nativa', 'Sim', '6-12', 'Pioneira', 'Diversidade', 'Anemocórica', 'Semicaducifólia', 'Semidecídua');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Espinheira-santa', 'Celastraceae', 'Monteverdia ilicifolia', '(Mart. ex Reissek) Biral', 'NULL', 'LC', 'Nativa', 'Não', '12', 'Não Pioneira', 'NULL', 'Zoocórica', 'Perene', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Bacupari', 'Clusiaceae', 'Garcinia cochinchinensis', '(Lour.) Choisy ', 'EN', 'NULL', 'Cultivada', 'Não', '8-10', 'NULL', 'NULL', 'Autocórica', 'Perene', 'Perenifólia');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Erva-baleeira', 'Cordiaceae ', 'Varronia curassavica', 'Jacq.', 'LC', 'NE', 'Nativa', 'Não', '3-5', 'Pioneira', 'Diversidade', 'Zoocórica', 'Perene', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Samambaia-preta', 'Dryopteridaceae', 'Rumohra adiantiformis', '(G. Forst.) Ching', 'NULL', 'NE', 'Nativa', 'Não', '1-2', 'NULL', 'NULL', 'NULL', 'Perene', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Mandioca', 'Euphorbiaceae', 'Manihot esculenta', 'Crantz  ', 'DD', 'NE', 'Nativa', 'Não', 'NULL', 'NULL', 'NULL', 'NULL', 'Perene', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Olho-de-cabra', 'Fabaceae', 'Ormosia arborea', '(Vell.) Harms ', 'NULL', 'LC', 'Nativa', 'Sim', '15-20', 'Não Pioneira', 'Diversidade', 'Autocórica//Zoocórica', 'NULL', 'Perenifólia');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Manacá-da-serra', 'Melastomataceae', 'Pleroma mutabile', '(Vell.) Triana', 'NULL', 'NE', 'Nativa', 'Sim', '5-10', 'Pioneira', 'NULL', 'NULL', 'NULL', 'Perenifólia');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Capiá', 'Moraceae', 'Dorstenia cayapia', 'Vell', 'NULL', 'LC', 'Nativa', 'Sim', '0,15-0,25', 'NULL', 'NULL', 'nul', 'NULL', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Cambuci', 'Myrtaceae', 'Campomanesia phaea', '(O.Berg) Landrum', 'LC', 'LC', 'Nativa', 'Sim', '3-5', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'NULL', 'Semidecídua');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Grumixama', 'Myrtaceae', 'Eugenia brasiliensis', 'Lam.  ', 'NULL', 'LC', 'Nativa', 'Não', '10-15', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'NULL', 'Perenifólia');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Uvaia', 'Myrtaceae', 'Eugenia pyriformis', 'Cambess.  ', 'LC', 'NE', 'Nativa', 'Não', '6-15', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'NULL', 'Semidecídua');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Cataia', 'Myrtaceae', 'Pimenta pseudocaryophyllus ', '(Gomes) Landrum', 'NULL', 'LC', 'Nativa', 'Não', '4-10', 'Pioneira', 'NULL', 'Zoocórica', 'NULL', 'Semidecídua');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Jabuticaba', 'Myrtaceae', 'Plinia peruviana', '(Poir.) Govaerts ', 'NULL', 'LC', 'Nativa', 'Não', '7-11', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'NULL', 'Semidecídua');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Araçá-vermelho//Araçá-amarelo', 'Myrtaceae', 'Psidium cattleyanum', 'Sabine  ', 'NULL', 'LC', 'Nativa', 'Sim', '3-6', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'NULL', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Araçá-roxo', 'Myrtaceae', 'Psidium myrtoides', 'O.Berg  ', 'NULL', 'LC', 'Nativa', 'Sim', '4-8', 'Não Pioneira', 'NULL', 'Zoocórica', 'NULL', 'Semidecídua');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Milho Crioulo', 'Poaceae', 'Zea mays', 'L. ', 'LC', 'NE', 'Cultivada', 'Não', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Café', 'Rubiaceae', 'Coffea arabica', 'L.  ', 'EN', 'NE', 'Naturalizada', 'Não', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Guaçatonga', 'Salicaceae', 'Casearia sylvestris', 'Sw.  ', 'NULL', 'NE', 'Nativa', 'Não', '6-20', 'Pioneira', 'Diversidade', 'Zoocórica', 'NULL', 'Perenifólia');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Maná-cubiu', 'Solanaceae', 'Solanum sessiliflorum', 'Dunal  ', 'NULL', 'NE', 'Nativa', 'Não', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Taboa', 'Typhaceae', 'Typha domingensis', '(Pers.)  ', 'NULL', 'NE', 'Nativa', 'Não', '1-2', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'NULL', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Flor-de-são-Miguel', 'Verbeneaceae', 'Petrea volubilis', 'L.', 'NULL', 'NE', 'Nativa', 'Não', '3-6', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Cataia', 'Winteracea', 'Drimys brasiliensis ', 'Miers', 'NULL', 'LC', 'Nativa', 'Não', '4-12', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'NULL', 'Perenifólia');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Bromélias', 'Bromeliacea', 'NULL', 'NULL', 'NULL', 'NULL', 'Nativa', 'Não', 'NULL', 'NULL', 'NULL', 'NULL', 'Perene', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Orquídeas', 'Orchideceae', 'NULL', 'NULL', 'NULL', 'NULL', 'Nativa', 'Não', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Helicôneas', 'Heliconeacea', 'NULL', 'NULL', 'NULL', 'NULL', 'Nativa', 'Não', 'NULL', 'NULL', 'NULL', 'NULL', 'Perene', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Clusias', 'Clusiaceae', 'NULL', 'NULL', 'NULL', 'NULL', 'Nativa', 'Não', 'NULL', 'NULL', 'NULL', 'NULL', 'Perene', 'NULL');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage) 
        VALUES ('Fofão', 'Calymperaceae', 'Syrrhopodon elongatus ', 'Sull.', 'NULL', 'NE', 'Nativa', 'Não', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL');