INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Aroeira-pimenteira//Pimenta-rosa', 'Anacardiaceae', 'Schinus terebinthifolia', 'Raddi  ', 'LC', 'LC', 'Nativa', 'Não', '5-10', 'Pioneira', 'Preenchimento', 'Zoocórica', 'Perene', 'Perenifólia', 'nan', 'set-out', 'jan-jul', '44000');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Imbé', 'Araceae', 'Philodendron imbe', 'Schott ex Kunth.', 'nan', 'NE', 'Nativa', 'Sim', 'nan', 'nan', 'nan', 'nan', 'Perene', 'Perenifólia', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Macaúba', 'Arecaceae', 'Acrocomia aculeata', '(Jacq.) Lodd. ex Mart.', 'nan', 'NE', 'Nativa', 'Não', '10-15', 'Não Pioneira', 'Preenchimento', 'Zoocórica', 'Perene', 'nan', 'nan', 'nan', 'nan', '98');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Tucum', 'Arecaceae', 'Bactris setosa', 'Mart.  ', 'LC', 'LC', 'Nativa', 'Sim', '8', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'nan', 'nan', 'nan', 'nan', 'nan', '580');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Juçara', 'Arecaceae', 'Euterpe edulis', 'Mart.  ', 'VU', 'VU', 'Nativa', 'Não', '5-12', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'Perene', 'nan', 'nan', 'nan', 'mar-jun', '750');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Jerivá', 'Arecaceae', 'Syagrus romanzoffiana', '(Cham.) Glassman ', 'LC', 'LC', 'Nativa', 'Não', '7 - 15', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'Anual', 'nan', 'nan', 'nan', 'nan', '500-700');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Pinhão', 'Auricariaceae', 'Araucaria angustifolia', '(Bertol.) Kuntze ', 'nan', 'EN', 'Nativa', 'Não', '20-50', 'Não Pioneira', 'Diversidade', 'Autocórica//Zoocórica', 'Perene', 'Perenifólia', 'nan', 'set-out', 'abr-mai', '150');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Caixeta', 'Bignoniaceae', 'Tabebuia cassinoides', '(Lam.) Dc.', 'nan', 'VU', 'Nativa', 'Sim', '6-12', 'Pioneira', 'Diversidade', 'Anemocórica', 'Semicaducifólia', 'Semidecídua', 'nan', 'jul-jan', 'out-mar', '37000');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Espinheira-santa', 'Celastraceae', 'Monteverdia ilicifolia', '(Mart. ex Reissek) Biral', 'nan', 'LC', 'Nativa', 'Não', '12', 'Não Pioneira', 'nan', 'Zoocórica', 'Perene', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Bacupari', 'Clusiaceae', 'Garcinia cochinchinensis', '(Lour.) Choisy ', 'EN', 'nan', 'Cultivada', 'Não', '8-10', 'nan', 'nan', 'Autocórica', 'Perene', 'Perenifólia', 'nan', 'nan', 'Set-Out', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Erva-baleeira', 'Cordiaceae ', 'Varronia curassavica', 'Jacq.', 'LC', 'NE', 'Nativa', 'Não', '3-5', 'Pioneira', 'Diversidade', 'Zoocórica', 'Perene', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Samambaia-preta', 'Dryopteridaceae', 'Rumohra adiantiformis', '(G. Forst.) Ching', 'nan', 'NE', 'Nativa', 'Não', '1-2', 'nan', 'nan', 'nan', 'Perene', 'nan', 'Entomofilia', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Mandioca', 'Euphorbiaceae', 'Manihot esculenta', 'Crantz  ', 'DD', 'NE', 'Nativa', 'Não', 'nan', 'nan', 'nan', 'nan', 'Perene', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Olho-de-cabra', 'Fabaceae', 'Ormosia arborea', '(Vell.) Harms ', 'nan', 'LC', 'Nativa', 'Sim', '15-20', 'Não Pioneira', 'Diversidade', 'Autocórica//Zoocórica', 'nan', 'Perenifólia', 'nan', 'out-nov', 'set-out', '800');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Manacá-da-serra', 'Melastomataceae', 'Pleroma mutabile', '(Vell.) Triana', 'nan', 'NE', 'Nativa', 'Sim', '5-10', 'Pioneira', 'nan', 'nan', 'nan', 'Perenifólia', 'nan', 'nov-fev//outono-inverno no planalto paulista', 'fev-mar', '3300000');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Capiá', 'Moraceae', 'Dorstenia cayapia', 'Vell', 'nan', 'LC', 'Nativa', 'Sim', '0,15-0,25', 'nan', 'nan', 'nul', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Cambuci', 'Myrtaceae', 'Campomanesia phaea', '(O.Berg) Landrum', 'LC', 'LC', 'Nativa', 'Sim', '3-5', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'nan', 'Semidecídua', 'nan', 'ago-nov', 'jan-fev', '29800');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Grumixama', 'Myrtaceae', 'Eugenia brasiliensis', 'Lam.  ', 'nan', 'LC', 'Nativa', 'Não', '10-15', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'nan', 'Perenifólia', 'nan', 'set-nov', 'nov-dez', '3500');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Uvaia', 'Myrtaceae', 'Eugenia pyriformis', 'Cambess.  ', 'LC', 'NE', 'Nativa', 'Não', '6-15', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'nan', 'Semidecídua', 'nan', 'ago-set', 'nov-dez', '1170');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Cataia', 'Myrtaceae', 'Pimenta pseudocaryophyllus ', '(Gomes) Landrum', 'nan', 'LC', 'Nativa', 'Não', '4-10', 'Pioneira', 'nan', 'Zoocórica', 'nan', 'Semidecídua', 'nan', 'jul-ag', 'out-nov', '218000');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Jabuticaba', 'Myrtaceae', 'Plinia peruviana', '(Poir.) Govaerts ', 'nan', 'LC', 'Nativa', 'Não', '7-11', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'nan', 'Semidecídua', 'nan', 'Set e fev', 'nan', '3300');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Araçá-vermelho//Araçá-amarelo', 'Myrtaceae', 'Psidium cattleyanum', 'Sabine  ', 'nan', 'LC', 'Nativa', 'Sim', '3-6', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Araçá-roxo', 'Myrtaceae', 'Psidium myrtoides', 'O.Berg  ', 'nan', 'LC', 'Nativa', 'Sim', '4-8', 'Não Pioneira', 'nan', 'Zoocórica', 'nan', 'Semidecídua', 'nan', 'out-dez', 'mai-jun', '730');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Milho Crioulo', 'Poaceae', 'Zea mays', 'L. ', 'LC', 'NE', 'Cultivada', 'Não', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Café', 'Rubiaceae', 'Coffea arabica', 'L.  ', 'EN', 'NE', 'Naturalizada', 'Não', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Guaçatonga', 'Salicaceae', 'Casearia sylvestris', 'Sw.  ', 'nan', 'NE', 'Nativa', 'Não', '6-20', 'Pioneira', 'Diversidade', 'Zoocórica', 'nan', 'Perenifólia', 'nan', 'jun-ago', 'set-nov', '84000');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Maná-cubiu', 'Solanaceae', 'Solanum sessiliflorum', 'Dunal  ', 'nan', 'NE', 'Nativa', 'Não', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Taboa', 'Typhaceae', 'Typha domingensis', '(Pers.)  ', 'nan', 'NE', 'Nativa', 'Não', '1-2', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Flor-de-são-Miguel', 'Verbeneaceae', 'Petrea volubilis', 'L.', 'nan', 'NE', 'Nativa', 'Não', '3-6', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'Set-Out', 'Set-Out', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Cataia', 'Winteracea', 'Drimys brasiliensis ', 'Miers', 'nan', 'LC', 'Nativa', 'Não', '4-12', 'Não Pioneira', 'Diversidade', 'Zoocórica', 'nan', 'Perenifólia', 'nan', 'dez-jan', 'mai', '9000');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Bromélias', 'Bromeliacea', 'nan', 'nan', 'nan', 'nan', 'Nativa', 'Não', 'nan', 'nan', 'nan', 'nan', 'Perene', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Orquídeas', 'Orchideceae', 'nan', 'nan', 'nan', 'nan', 'Nativa', 'Não', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Helicôneas', 'Heliconeacea', 'nan', 'nan', 'nan', 'nan', 'Nativa', 'Não', 'nan', 'nan', 'nan', 'nan', 'Perene', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Clusias', 'Clusiaceae', 'nan', 'nan', 'nan', 'nan', 'Nativa', 'Não', 'nan', 'nan', 'nan', 'nan', 'Perene', 'nan', 'nan', 'nan', 'nan', 'nan');
INSERT INTO species (vernacularName, family, scientificName, authorship, threatenedStatusIUCN, threatenedStatusCNCFLORA, origin, endemism, height, successionalStage, functionalGroup, dispersalSyndrome, lifeCycle, foliage, pollinationSyndrome, flowerFenology, fruitFenology, quantitySeed) 
        VALUES ('Fofão', 'Calymperaceae', 'Syrrhopodon elongatus ', 'Sull.', 'nan', 'NE', 'Nativa', 'Não', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan');